wbEcsc/ViewModels/DesignationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using wbEcsc.Models.Application;


namespace wbEcsc.ViewModels
{
    public class DesignationViewModel
    {
        public List<Field> LsitField { get; set; }
        public Designation_MD SelectedDesignation { get; set; }
        public List<Designation_MD> Designation_list { get; set; }
    }
}

wbEcsc/Controllers/Administration/Master/DesignationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using wbEcsc.App_Codes.BLL;
using wbEcsc.Models.Application;
using wbEcsc.ViewModels;
using System.Data;
using wbEcsc.App_Start;

namespace wbEcsc.Controllers.Master
{
    [SecuredFilter]
    public class DesignationController : Controller
    {
        // GET: Designation
        Designation desig_bll = new Designation();
        Designation_MD desig = new Designation_MD();
        DesignationViewModel desig_viewmodel = new DesignationViewModel();
        public ActionResult Index(int? id)
        {
            desig_viewmodel.Designation_list = desig_bll.Get_Designation();
            desig_viewmodel.SelectedDesignation = desig;
            desig_viewmodel.LsitField = desig_bll.GetField();
            if(id!=null)
            {
                var selectedDesig =(from d in desig_viewmodel.Designation_list where d.DesignationID.Equals(id) select new { d.DesignationID, d.Designation });
                foreach (var d in selectedDesig)
                {
                    desig_viewmodel.SelectedDesignation.Designation = d.Designation;
                    desig_viewmodel.SelectedDesignation.DesignationID = d.DesignationID;
                }           
            }                
            return View(desig_viewmodel);
        }
        public ActionResult Save(Designation_MD desig)
        {
            try
            {               
                DataTable dt= desig_bll.Save(desig);
                TempData["ErrorCode"] = dt.Rows[0][0].ToString();
                TempData["Massage"] = dt.Rows[0][1].ToString();               
               
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

wbEcsc/Views/Designation/Index.cshtml
@model wbEcsc.ViewModels.DesignationViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="~/Scripts/AppJs/Designation.js"></script>
@if(TempData["Massage"]!=null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@TempData["Massage"]");
        };
    </script>
}

@foreach (var field in Model.LsitField)
{
    if (1 == field.FieldID)
    {
        ViewBag.Designation = field.FieldName;
        ViewBag.Mand = field.IsMand.Equals(1) ? "*" : " ";
    }

    if (2 == field.FieldID)
    {
        ViewBag.SaveButton = field.FieldName;
    }
    if (3 == field.FieldID)
    {
        ViewBag.UpdateField = field.FieldName;
    }
    if (5 == field.FieldID)
    {
        ViewBag.UpdateButton = field.FieldName;
    }
}

<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="form-group">
                <label> Designation Master </label>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                @using (Html.BeginForm("Save", "Designation", FormMethod.Post))
                {
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-xs-offset-4">                       
                            <div class="form-group">                               
                                <label>@ViewBag.Designation</label>                              
                                <span style="color:red;">@ViewBag.Mand</span>                             
                                <input type="text" name="Designation" onkeyup="SearchTable()" onblur="SearchTable()" value="@Model.SelectedDesignation.Designation" id="txtDesignation" class="form-control" />
                                <input type="hidden" name="DesignationID" value="@Model.SelectedDesignation.DesignationID" id="hdnDesignationID" />                                
                            </div>
                            <div class="form-group">    
                                @if (Model.SelectedDesignation.DesignationID == null)
                                {
                                    <input type="submit" value="@ViewBag.SaveButton" name="btnsubmit" id="btnSubmit" class="btn btn-info " />
                                }
                                else
                                {
                                    <input type="submit" value="@ViewBag.UpdateButton" name="btnsubmit" id="btnSubmit" class="btn btn-info " />
                                }
                                <input type="reset" value="Refresh" name="btnsubmit" id="btnRefresh" onclick="javascript:window.location.href='Index'" class="btn btn-info" />
                            </div>                        
                    </div>
                }
            </div>
            <div class="row">
                <div class="container-fluid">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="row text-center">
                                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                    <div class="form-group"><label>Serial No</label></div>
                                </div>
                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                                    <div class="form-group"><label>Designation</label></div>
                                </div>
                                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                    <div class="form-group"><label>Update</label></div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body clstbl" style="max-height:500px;overflow-y:scroll;">
                            @foreach (var designation in Model.Designation_list)
                            {
                                var index = Model.Designation_list.IndexOf(designation) + 1;
                                <div class="row clsrow border-top">
                                    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">@index</div>
                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 clsDesignation">@designation.Designation</div>
                                    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 text-center" title="Click to Edit This Record"> @Html.ActionLink((string)ViewBag.UpdateField, "Index", "Designation", new { id = designation.DesignationID }, null) </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>